steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA',
        '-f',
        './docker/job-board.docker',
        '.'
      ]

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'
      ]

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA',
        '--platform',
        'managed',
        '--region',
        '$_REGION',
        '--allow-unauthenticated',
        '--set-env-vars',
        'APP_PORT=9876,JOB_BOARD_PORT=9876',
        '--port',
        '9876',
        '--quiet'
      ]

substitutions:
  _IMAGE_NAME: 'job-board'
  _REPO_NAME: 'gcp-job-board-service'
  _REPO_OWNER: 'tnvpandian'
  _BRANCH_NAME: 'develop'
  _REGION: 'europe-west2'
  _SERVICE_NAME: 'cloud-apps-job-board'
logsBucket: "gs://tnvp-gcp-services-logs"

# Trigger settings
#trigger:
#  branch: '^develop$'
